# Generated by Django 2.2.4 on 2019-08-06 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20171222_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='キャリアレベル')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, max_length=20, verbose_name='キャリアレベル'),
        ),
    ]
