# Generated by Django 2.2.4 on 2019-08-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20190806_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.ManyToManyField(to='employee.Status', verbose_name='部活'),
        ),
    ]
