# Generated by Django 2.2.4 on 2019-08-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20190806_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.ManyToManyField(default='lv.11', to='employee.Status', verbose_name='キャリアレベル'),
        ),
    ]
